version: "3.3"

services:
    {% if ENVIRONMENT == "DEV" %}
    pot-imana-rabbitmq-broker-{{ PLANT_CODE.lower() }}:
    {% elif ENVIRONMENT == "STAG" or ENVIRONMENT == "PROD" %}
    pot-anima-rabbitmq-broker-{{ PLANT_CODE.lower() }}:
    {% endif %}
        image: rabbitmq:3-management
        {% if ENVIRONMENT == "DEV" %}
        container_name: pot-imana-rabbitmq-broker-{{ PLANT_CODE.lower() }}
        {% elif ENVIRONMENT == "STAG" or ENVIRONMENT == "PROD" %}
        container_name: pot-anima-rabbitmq-broker-{{ PLANT_CODE.lower() }}
        {% endif %}
        hostname: rabbitmq-broker-{{ PLANT_CODE.lower() }}
        restart: always
        user: root
        privileged: true
        deploy:
            replicas: 1
        volumes:
            - {{ SERVICE_CONFIG_DIR }}/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
            - {{ SERVICE_CONFIG_DIR }}/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
            - {{ SERVICE_CONFIG_DIR }}/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
        environment:
            https_proxy: ${https_proxy}
        networks:
            - anima_network
        healthcheck:
            test: ["CMD", "rabbitmqctl", "list_connections"]
    
    {{ APPLICATION_SERVICE_NAME }}-{{ PLANT_CODE.lower() }}:
        {% if ENVIRONMENT == "DEV" %}
        image: europe-west1-docker.pkg.dev/pot-test-environment/pot-imana-dok/potimanabe8:dev-dev-pot-imana-first_0.0.52_2859d66
        {% elif ENVIRONMENT == "STAG" %}
        image: europe-west1-docker.pkg.dev/pot-test-environment/pot-anima-dok/potanimabe8:dev-MF20240521_0.0.533_c3b81da
        {% elif ENVIRONMENT == "PROD" %}
        image: europe-west1-docker.pkg.dev/plants-of-tomorrow-poc/pot-anima-dok/potanimabe8:main_0.0.536_e9678ab
        {% endif %}
        container_name: {{ APPLICATION_SERVICE_NAME }}-{{ PLANT_CODE.lower() }}
        labels:
            PLANT_CODE: {{ PLANT_CODE }}
        restart: always
        user: root
        {% if ENVIRONMENT == "DEV" %}
        depends_on:
            pot-imana-rabbitmq-broker-{{ PLANT_CODE.lower() }}:
                condition: service_healthy
        {% elif ENVIRONMENT == "STAG" or ENVIRONMENT == "PROD" %}
        depends_on:
            pot-anima-rabbitmq-broker-{{ PLANT_CODE.lower() }}:
                condition: service_healthy
        {% endif %}
        {% if ENVIRONMENT == "PROD" %}
        volumes:
            - {{ KEYS_DIR }}/pot-anima-{{ ENVIRONMENT.lower() }}:/srv/pot/anima/config/secrets/gcp_credential.json
            - {{ KEYS_DIR }}/gcp-{{ ENVIRONMENT.lower() }}-pot-anima-restapi-secret:/srv/pot/anima/config/secrets/backend_apikey.json
        {% elif ENVIRONMENT == "STAG" %}
        volumes:
            - {{ KEYS_DIR }}/gcp-{{ ENVIRONMENT.lower() }}-pot-anima-bec:/srv/pot/anima/config/secrets/gcp_credential.json
            - {{ KEYS_DIR }}/gcp-{{ ENVIRONMENT.lower() }}-pot-anima-restapi-secret:/srv/pot/anima/config/secrets/backend_apikey.json
        {% elif ENVIRONMENT == "DEV" %}
        volumes:
            - {{ KEYS_DIR }}/pot-{{ ENVIRONMENT.lower() }}2-imana-be1_gcp-pot:/srv/pot/imana/config/secrets/gcp_credential.json
            - {{ KEYS_DIR }}/gcp-{{ ENVIRONMENT.lower() }}2-pot-anima-restapi-secret:/srv/pot/imana/config/secrets/backend_apikey.json
        {% endif %}
        environment:
            APP_ENV: {{ ENVIRONMENT }}
            APP_PLANT: {{ PLANT_CODE }}
            https_proxy: ${https_proxy}
            {% if ENVIRONMENT == "STAG" or ENVIRONMENT == "PROD" %}
            GOOGLE_APPLICATION_CREDENTIALS: /srv/pot/anima/config/secrets/gcp_credential.json
            {% elif ENVIRONMENT == "DEV" %}
            GOOGLE_APPLICATION_CREDENTIALS: /srv/pot/imana/config/secrets/gcp_credential.json
            {% endif %}
        networks:
            - anima_network
networks:
    anima_network:
        name: anima_network
